### ISSUE TITLE
Error when renaming empty folder

### ISSUE THREAD

**Issue by kapersoft** [ctf0/vscode-php-class-generator#2]
Hi! I love this plugin, it was one of features missing in my VSCode setup for PHP.

When I renamed an empty folder, the `Updating Please Wait` progress window won't close. In the Window log of the Output view the following error appears:
```
2022-12-14 17:49:22.260 [error] Expected a string: TypeError: Expected a string
    at oe (/Users/jwkaper/.vscode/extensions/ctf0.php-class-generator-0.2.4/out/main.js:22:4961)
    at processor (/Users/jwkaper/.vscode/extensions/ctf0.php-class-generator-0.2.4/out/main.js:22:6869)
    at /Users/jwkaper/.vscode/extensions/ctf0.php-class-generator-0.2.4/out/main.js:17:16255
    at Array.reduce (<anonymous>)
    at Va.exports (/Users/jwkaper/.vscode/extensions/ctf0.php-class-generator-0.2.4/out/main.js:17:16239)
    at /Users/jwkaper/.vscode/extensions/ctf0.php-class-generator-0.2.4/out/main.js:17:16692
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

I guess there should be a check added to assure the renamed folder contain any files to proces?

**Comment by ctf0** [comment]
ah ok, i didnt test this case, will add it as well, thank you for reporting ❤️
